In [95]:
import numpy as np
import torch

original_data = np.genfromtxt('../../../working_data/normalised_delta_updrs_sigfall.csv', delimiter=',', skip_header=True)
_, n_columns = original_data.shape

data = original_data[:,0:(n_columns - 1)]
labels = original_data[:,(n_columns - 1)]

full_train = original_data[0:1100]
full_test  = original_data[1101:1452]

xx_train = data[0:1000]
xx_test = data[1001:1400]
yy_test  = labels[1001:1400]
yy_train = labels[0:1000]

full_train.shape

(1100, 15)

In [126]:
# Create data loaders for our datasets; shuffle for training, not for validation
training_loader = torch.utils.data.DataLoader(full_train, batch_size=4, shuffle=True, num_workers=2)
validation_loader = torch.utils.data.DataLoader(full_test, batch_size=4, shuffle=False, num_workers=2)

In [122]:
class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()

        self.input = torch.nn.Linear(13, 25) # 14-25-10-1
        self.activation = torch.nn.Sigmoid()
        self.hidden1 = torch.nn.Linear(25, 10)
        self.output = torch.nn.Linear(10, 1)
        
        torch.nn.init.xavier_uniform_(self.input.weight)
        torch.nn.init.zeros_(self.input.bias)
        torch.nn.init.xavier_uniform_(self.hidden1.weight)
        torch.nn.init.zeros_(self.hidden1.bias)
        torch.nn.init.xavier_uniform_(self.output.weight)
        torch.nn.init.zeros_(self.output.weight)

    def forward(self, x):
        x = self.input(x)
        x = self.activation(x)
        x = self.hidden1(x)
        x = self.activation(x)
        x = self.output(x)
        x = self.activation(x)
        return x
    
model = TinyModel()
model.float()

TinyModel(
  (input): Linear(in_features=13, out_features=25, bias=True)
  (activation): Sigmoid()
  (hidden1): Linear(in_features=25, out_features=10, bias=True)
  (output): Linear(in_features=10, out_features=1, bias=True)
)

In [98]:
# Optimizers specified in the torch.optim package
optimizer = torch.optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [99]:
# Loss function
loss_fn = torch.nn.BCELoss()


In [127]:
# Test the nn

x = full_train[3]
x_tensor = torch.from_numpy(x[0:13]).float()
y = model(x_tensor)

print(y)

tensor([0.5310], grad_fn=<SigmoidBackward0>)


In [128]:
for i, x in enumerate(training_loader):
    label = x[0,14].float().reshape(1)
    inputs = x[0,0:13].float()

    # Zero your gradients for every batch!
    optimizer.zero_grad()

    # Make predictions for this batch
    y = model(inputs)
    # Compute the loss and its gradients
    print(y)
    print(label)
    loss = loss_fn(y, label)
    loss.backward()

    # Adjust learning weights
    optimizer.step()
   
    # so it actually trains now 
    # so why does it keep plopping out the same result?

tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([1.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310], grad_fn=<SigmoidBackward0>)
tensor([0.])
tensor([0.5310